// Routed walking distances from Denver hotels to venues.
//
// METHOD — stated here and on every page that renders it:
// These are street-network WALKING distances produced by OSRM pedestrian
// routing over OpenStreetMap data (routing.openstreetmap.de, foot profile),
// measured from each hotel's stored coordinates to the venue entrance. They
// follow real pavements and crossings, so they account for the things that
// make straight-line distance useless in Denver: the Consolidated Main Line
// rail corridor, Speer Boulevard, Cherry Creek and the Platte, which
// pedestrians cross only at specific bridges.
//
// They are routed, not walked. Nobody has timed these on foot. Walk times are
// derived from distance at a stated 3 mph, not reported by the router, so the
// assumption is visible rather than buried in a routing engine's defaults.
//
// Why this was worth doing: against straight-line distance the routed figures
// run 23–82% longer, and the ORDER changes. SpringHill Suites is the closest
// hotel either way, but its straight-line 0.20 mi becomes 0.36 mi on foot —
// an 82% penalty — because the rail corridor forces a detour. Any guide
// publishing straight-line numbers as walk times is wrong by a quarter to a
// half, and wrong unevenly.
//
// Data © OpenStreetMap contributors, ODbL. Routing by OSRM.

/** Metres, routed on foot. Keyed by venue guide href, then hotel slug. */
export const VENUE_WALK_METRES: Record<string, Record<string, number>> = {
  "/hotels/near-coors-field": {
    "the-rally-hotel-at-mcgregor-square": 198,
    "the-maven-hotel-at-dairy-block": 412,
    "hotel-diablo": 431,
    "the-crawford-hotel": 582,
    "hilton-garden-inn-denver-union-station": 743,
    "nativ-hotel": 777,
    "thompson-denver-by-hyatt": 818,
    "limelight-denver": 825,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 853,
    "the-westin-denver-downtown": 963,
    "hyatt-centric-downtown-denver": 1101,
    "residence-inn-by-marriott-denver-city-center": 1123,
    "kasa-union-station-denver": 1162,
    "renaissance-denver-downtown-city-center-hotel": 1238,
    "hilton-denver-city-center": 1282,
    "courtyard-by-marriott-denver-downtown": 1286,
    "the-curtis-park-club": 1322,
    "four-seasons-hotel-denver": 1408,
    "hotel-teatro": 1408,
    "springhill-suites-by-marriott-denver-downtown": 1454,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 1485,
    "kasa-rino-denver": 1515,
    "kasa-lohi-denver": 1519,
    "holiday-inn-express-denver-downtown-by-ihg": 1522,
    "home2-by-hilton-denver-downtown-convention-center": 1543,
    "tru-by-hilton-denver-downtown-convention-center": 1544,
    "aloft-by-marriott-denver-downtown": 1582,
    "warwick-denver": 1727,
    "embassy-suites-by-hilton-denver-downtown-convention-center": 1749,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 1794,
    "hampton-inn-suites-denver-downtown-convention-center": 1799,
    "hyatt-regency-denver-at-colorado-convention-center": 1837,
    "sheraton-denver-downtown-hotel": 1891,
    "hilton-garden-inn-denver-downtown": 1908,
    "sonesta-denver-downtown": 1914,
    "hyatt-place-denverdowntown": 1968,
    "hyatt-house-denverdowntown": 1970,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 2155,
    "the-source-hotel": 2234,
    "fairfield-by-marriott-inn-suites-denver-downtown": 2286,
    "espadn-lohi": 2288,
    "the-artesian": 2350,
    "hampton-inn-suites-denver-speer-boulevard": 2356,
    "ac-hotel-denver-rino": 2780,
    "courtyard-by-marriott-denver-downtown-west": 3755,
  },
  "/hotels/near-ball-arena": {
    "springhill-suites-by-marriott-denver-downtown": 586,
    "limelight-denver": 936,
    "nativ-hotel": 995,
    "hotel-teatro": 1038,
    "the-crawford-hotel": 1076,
    "four-seasons-hotel-denver": 1078,
    "thompson-denver-by-hyatt": 1100,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 1218,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 1245,
    "the-westin-denver-downtown": 1320,
    "the-maven-hotel-at-dairy-block": 1359,
    "courtyard-by-marriott-denver-downtown": 1452,
    "kasa-union-station-denver": 1453,
    "embassy-suites-by-hilton-denver-downtown-convention-center": 1493,
    "aloft-by-marriott-denver-downtown": 1506,
    "home2-by-hilton-denver-downtown-convention-center": 1506,
    "hilton-garden-inn-denver-union-station": 1513,
    "the-rally-hotel-at-mcgregor-square": 1527,
    "tru-by-hilton-denver-downtown-convention-center": 1577,
    "renaissance-denver-downtown-city-center-hotel": 1629,
    "hampton-inn-suites-denver-speer-boulevard": 1646,
    "hyatt-regency-denver-at-colorado-convention-center": 1663,
    "hilton-garden-inn-denver-downtown": 1696,
    "fairfield-by-marriott-inn-suites-denver-downtown": 1698,
    "hampton-inn-suites-denver-downtown-convention-center": 1717,
    "hyatt-place-denverdowntown": 1722,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 1723,
    "hyatt-house-denverdowntown": 1724,
    "residence-inn-by-marriott-denver-city-center": 1746,
    "hyatt-centric-downtown-denver": 1809,
    "espadn-lohi": 1834,
    "sonesta-denver-downtown": 1839,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 1852,
    "hotel-diablo": 1924,
    "hilton-denver-city-center": 2003,
    "sheraton-denver-downtown-hotel": 2097,
    "kasa-lohi-denver": 2221,
    "holiday-inn-express-denver-downtown-by-ihg": 2223,
    "the-artesian": 2256,
    "courtyard-by-marriott-denver-downtown-west": 2412,
    "kasa-rino-denver": 2662,
    "warwick-denver": 2696,
    "the-curtis-park-club": 2736,
    "the-source-hotel": 3592,
    "ac-hotel-denver-rino": 4138,
  },
  "/hotels/near-convention-center": {
    "embassy-suites-by-hilton-denver-downtown-convention-center": 119,
    "hyatt-regency-denver-at-colorado-convention-center": 204,
    "hilton-garden-inn-denver-downtown": 236,
    "aloft-by-marriott-denver-downtown": 246,
    "hampton-inn-suites-denver-downtown-convention-center": 258,
    "hyatt-place-denverdowntown": 259,
    "hyatt-house-denverdowntown": 260,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 263,
    "home2-by-hilton-denver-downtown-convention-center": 286,
    "tru-by-hilton-denver-downtown-convention-center": 288,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 344,
    "sonesta-denver-downtown": 379,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 388,
    "hotel-teatro": 426,
    "courtyard-by-marriott-denver-downtown": 546,
    "four-seasons-hotel-denver": 563,
    "sheraton-denver-downtown-hotel": 573,
    "hilton-denver-city-center": 593,
    "renaissance-denver-downtown-city-center-hotel": 596,
    "residence-inn-by-marriott-denver-city-center": 714,
    "hyatt-centric-downtown-denver": 737,
    "holiday-inn-express-denver-downtown-by-ihg": 805,
    "the-westin-denver-downtown": 873,
    "thompson-denver-by-hyatt": 1025,
    "springhill-suites-by-marriott-denver-downtown": 1033,
    "nativ-hotel": 1226,
    "warwick-denver": 1278,
    "the-crawford-hotel": 1498,
    "limelight-denver": 1501,
    "the-maven-hotel-at-dairy-block": 1592,
    "the-rally-hotel-at-mcgregor-square": 1830,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 1850,
    "the-curtis-park-club": 1862,
    "hotel-diablo": 1940,
    "kasa-union-station-denver": 2063,
    "hilton-garden-inn-denver-union-station": 2113,
    "hampton-inn-suites-denver-speer-boulevard": 2493,
    "fairfield-by-marriott-inn-suites-denver-downtown": 2545,
    "espadn-lohi": 2681,
    "kasa-lohi-denver": 2869,
    "the-artesian": 2911,
    "kasa-rino-denver": 2960,
    "courtyard-by-marriott-denver-downtown-west": 3326,
    "the-source-hotel": 3455,
    "ac-hotel-denver-rino": 4001,
  },
  "/hotels/near-empower-field": {
    "courtyard-by-marriott-denver-downtown-west": 878,
    "hampton-inn-suites-denver-speer-boulevard": 1776,
    "fairfield-by-marriott-inn-suites-denver-downtown": 1828,
    "springhill-suites-by-marriott-denver-downtown": 1836,
    "espadn-lohi": 1964,
    "hotel-teatro": 2246,
    "four-seasons-hotel-denver": 2286,
    "thompson-denver-by-hyatt": 2406,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 2425,
    "nativ-hotel": 2427,
    "limelight-denver": 2520,
    "the-westin-denver-downtown": 2527,
    "kasa-union-station-denver": 2640,
    "courtyard-by-marriott-denver-downtown": 2659,
    "the-crawford-hotel": 2659,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 2673,
    "embassy-suites-by-hilton-denver-downtown-convention-center": 2681,
    "aloft-by-marriott-denver-downtown": 2713,
    "home2-by-hilton-denver-downtown-convention-center": 2713,
    "tru-by-hilton-denver-downtown-convention-center": 2764,
    "the-maven-hotel-at-dairy-block": 2792,
    "hyatt-place-denverdowntown": 2799,
    "hyatt-house-denverdowntown": 2801,
    "renaissance-denver-downtown-city-center-hotel": 2836,
    "hyatt-regency-denver-at-colorado-convention-center": 2845,
    "hilton-garden-inn-denver-downtown": 2850,
    "the-artesian": 2855,
    "kasa-lohi-denver": 2860,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 2869,
    "hampton-inn-suites-denver-downtown-convention-center": 2872,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 2877,
    "sonesta-denver-downtown": 2924,
    "residence-inn-by-marriott-denver-city-center": 2954,
    "hilton-garden-inn-denver-union-station": 3012,
    "the-rally-hotel-at-mcgregor-square": 3012,
    "hyatt-centric-downtown-denver": 3017,
    "sheraton-denver-downtown-hotel": 3071,
    "hilton-denver-city-center": 3211,
    "holiday-inn-express-denver-downtown-by-ihg": 3328,
    "hotel-diablo": 3356,
    "warwick-denver": 3781,
    "the-curtis-park-club": 3944,
    "kasa-rino-denver": 4245,
    "the-source-hotel": 5159,
    "ac-hotel-denver-rino": 5706,
  },
  "/hotels/near-mission-ballroom": {
    "ac-hotel-denver-rino": 254,
    "the-source-hotel": 301,
    "kasa-rino-denver": 1500,
    "hotel-diablo": 2096,
    "the-curtis-park-club": 2228,
    "the-rally-hotel-at-mcgregor-square": 2619,
    "hilton-garden-inn-denver-union-station": 2658,
    "the-maven-hotel-at-dairy-block": 2728,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 2818,
    "limelight-denver": 2983,
    "the-crawford-hotel": 2988,
    "thompson-denver-by-hyatt": 3075,
    "hyatt-centric-downtown-denver": 3082,
    "nativ-hotel": 3092,
    "the-westin-denver-downtown": 3112,
    "residence-inn-by-marriott-denver-city-center": 3123,
    "kasa-union-station-denver": 3127,
    "hilton-denver-city-center": 3170,
    "renaissance-denver-downtown-city-center-hotel": 3241,
    "courtyard-by-marriott-denver-downtown": 3333,
    "kasa-lohi-denver": 3400,
    "holiday-inn-express-denver-downtown-by-ihg": 3402,
    "tru-by-hilton-denver-downtown-convention-center": 3482,
    "warwick-denver": 3496,
    "four-seasons-hotel-denver": 3522,
    "home2-by-hilton-denver-downtown-convention-center": 3533,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 3544,
    "aloft-by-marriott-denver-downtown": 3557,
    "hotel-teatro": 3563,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 3674,
    "embassy-suites-by-hilton-denver-downtown-convention-center": 3678,
    "hampton-inn-suites-denver-downtown-convention-center": 3680,
    "hyatt-regency-denver-at-colorado-convention-center": 3717,
    "springhill-suites-by-marriott-denver-downtown": 3745,
    "sheraton-denver-downtown-hotel": 3771,
    "hilton-garden-inn-denver-downtown": 3789,
    "sonesta-denver-downtown": 3794,
    "hyatt-place-denverdowntown": 3849,
    "hyatt-house-denverdowntown": 3850,
    "the-artesian": 3965,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 4036,
    "fairfield-by-marriott-inn-suites-denver-downtown": 4399,
    "espadn-lohi": 4401,
    "hampton-inn-suites-denver-speer-boulevard": 4469,
    "courtyard-by-marriott-denver-downtown-west": 5868,
  },
  "/hotels/near-national-western": {
    "ac-hotel-denver-rino": 1337,
    "the-source-hotel": 1814,
    "kasa-rino-denver": 2710,
    "the-curtis-park-club": 3547,
    "hotel-diablo": 3561,
    "the-rally-hotel-at-mcgregor-square": 4085,
    "hilton-garden-inn-denver-union-station": 4124,
    "the-maven-hotel-at-dairy-block": 4194,
    "hotel-indigo-denver-downtown-union-station-by-ihg": 4283,
    "limelight-denver": 4448,
    "the-crawford-hotel": 4454,
    "thompson-denver-by-hyatt": 4541,
    "hyatt-centric-downtown-denver": 4547,
    "nativ-hotel": 4558,
    "the-westin-denver-downtown": 4578,
    "residence-inn-by-marriott-denver-city-center": 4588,
    "kasa-union-station-denver": 4592,
    "hilton-denver-city-center": 4636,
    "renaissance-denver-downtown-city-center-hotel": 4706,
    "courtyard-by-marriott-denver-downtown": 4798,
    "warwick-denver": 4840,
    "kasa-lohi-denver": 4852,
    "holiday-inn-express-denver-downtown-by-ihg": 4868,
    "tru-by-hilton-denver-downtown-convention-center": 4947,
    "four-seasons-hotel-denver": 4987,
    "home2-by-hilton-denver-downtown-convention-center": 4998,
    "the-curtis-denver---a-doubletree-by-hilton-hotel": 5009,
    "aloft-by-marriott-denver-downtown": 5023,
    "hotel-teatro": 5028,
    "homewood-suites-by-hilton-denver-downtown-convention-center": 5139,
    "embassy-suites-by-hilton-denver-downtown-convention-center": 5144,
    "hampton-inn-suites-denver-downtown-convention-center": 5145,
    "hyatt-regency-denver-at-colorado-convention-center": 5183,
    "springhill-suites-by-marriott-denver-downtown": 5210,
    "sheraton-denver-downtown-hotel": 5237,
    "hilton-garden-inn-denver-downtown": 5254,
    "sonesta-denver-downtown": 5259,
    "the-artesian": 5265,
    "hyatt-place-denverdowntown": 5314,
    "hyatt-house-denverdowntown": 5316,
    "the-slate-hotel-denver-downtown-tapestry-by-hilton": 5501,
    "fairfield-by-marriott-inn-suites-denver-downtown": 5864,
    "espadn-lohi": 5866,
    "hampton-inn-suites-denver-speer-boulevard": 5934,
    "courtyard-by-marriott-denver-downtown-west": 7334,
  },
};

/** When each venue's routing was last run. Shown on the page. */
export const VENUE_WALK_DATED: Record<string, string> = {
  "/hotels/near-coors-field": "2026-08-29",
  "/hotels/near-ball-arena": "2026-08-29",
  "/hotels/near-convention-center": "2026-08-29",
  "/hotels/near-empower-field": "2026-08-29",
  "/hotels/near-mission-ballroom": "2026-08-29",
  "/hotels/near-national-western": "2026-08-29",
};

export const METRES_PER_MILE = 1609.34;
/** Walking pace used to derive times from distance. Stated on the page. */
export const WALK_MPH = 3;

export function walkMetres(venueHref: string, hotelSlug: string): number | null {
  return VENUE_WALK_METRES[venueHref]?.[hotelSlug] ?? null;
}

export function metresToMiles(m: number): number {
  return m / METRES_PER_MILE;
}

export function walkMinutes(metres: number): number {
  return Math.round((metresToMiles(metres) / WALK_MPH) * 60);
}

export type WalkBand = "short" | "real" | "wheels" | "ride";

/** Bands on routed distance — the number people actually walk. */
export function walkBand(metres: number): WalkBand {
  const mi = metresToMiles(metres);
  if (mi <= 0.75) return "short";
  if (mi <= 1.5) return "real";
  if (mi <= 2) return "wheels";
  return "ride";
}

export const WALK_BANDS: Record<WalkBand, { label: string; note: string }> = {
  short: {
    label: "Walk it",
    note: "Under 0.75 miles on foot, about fifteen minutes at a normal pace. Walk it and don't think about parking.",
  },
  real: {
    label: "A real walk, not a stroll",
    note: "0.75 to 1.5 miles — fifteen to thirty minutes each way. Fine before a game on a decent evening. Less fun at eleven at night in February, in the wrong shoes, after a few beers.",
  },
  wheels: {
    label: "Grab a scooter or a bike",
    note: "1.5 to 2 miles. That's a long walk and a very short ride. Lime and Bird scooters are thick on the ground across downtown and LoDo, and the B-cycle docks cover most of this ground too — five minutes and a couple of dollars instead of half an hour on foot.",
  },
  ride: {
    label: "Uber or Lyft",
    note: "Over 2 miles. Just get a car. Light rail only helps if your hotel is near a station too, and Denver's system is good along a few corridors and no use off them — so check your specific hotel rather than assuming downtown means connected.",
  },
};
